version: '3'
services:
  db:
    image: postgres
    # container_name: postgres
    ports:
      - '5432:5432'
    # ports:
    #   - ${POSTGRES_PORT}:5432
    restart: always
    env_file:
      - .env
    # environment:
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      # - ./pgdata:/var/lib/postgresql/data
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
